"use client"
import { ChakraProvider } from '@chakra-ui/react'
import Nabvar from '../components/Navbar';
import HeroSection from '@/components/HeroSection';
import Features from '../components/Features';
import Testimonials from '@/components/Testimonials';
import Footer from '../components/Footer';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <ChakraProvider>
          <Nabvar />
          <HeroSection />
          <Features />
          <Testimonials />
          <Footer />
          {children}
        </ChakraProvider>
      </body>
    </html>
  )
}
